/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'c53215a' at '8/7/18 9:56 AM' with Gradle 3.2.1
 *
 * @author c53215a, @date 8/7/18 9:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
